### ISSUE TITLE
Project Zomboid data loss with "servername stop"

### ISSUE THREAD

**Issue by DobriyDed** [GameServerManagers/LinuxGSM#1620]
Hi! 
After issuing "pzserver stop" command  (PZ =project zomboid) , 
server terminates with data loss. Player building structures suffer, sometimes inventory items missing etc.
To correctly shutdown server task,  RCON or server console "quit" command must be entered

**Comment by DobriyDed** [comment]
Incorrect method of shutdown used for app id 380870 (Prozect zomboid)

Graceful logout must be done by sending "quit" command to tmux session
during LGSM "pzserver stop" i see in logs 

`i/o error 
java.io.IOException: 
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:272)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
`

After issuing 
`tmux send -t 0 quit ENTER`

i've got 
`Quit
1507108636135 SaveAll took 23.188929 ms
1507108636137 reanimate: saved 0 zombies
Saving finish
1507108636138 Saving took 26.083375 ms
1507108642213 waiting for UdpEngine thread termination
1507108642224 znet: Java_zombie_core_raknet_RakNetPeerInterface_Shutdown
1507108642224 znet: Shutting down Steam Game Server
1507108643420 znet: Java_zombie_core_znet_SteamUtils_n_1Shutdown`
