### ISSUE TITLE
Project Zomboid server with "beta vehicle" error: 

### ISSUE THREAD

**Issue by Culvanen** [GameServerManagers/LinuxGSM#1764]
Hi,
i want use beta vehicle into the project zomboid server so i have add 

branch="-beta vehicle"

into pzserver.cfg but after this my server won't start.

Here is the result of debug:

```
`[ INFO ] Debug pzserver: Stopping any running servers
[ INFO ] Stopping pzserver: Serveur test is already stopped
[  OK  ] Debug pzserver: Starting debug
64-bit java detected
pzexe: about to run java hack to locate libjvm.so...
pzexe: executing "java -classpath pzexe.jar -Djava.library.path=. zombie.pzexe"
pzexe.java: loading shared library "pzexe_jni64"
JVM=/home/pzserver/serverfiles/jre64/lib/amd64/server/libjvm.so
pzexe config file: /home/pzserver/serverfiles/ProjectZomboid64.json
pzexe: mainClass: zombie/network/GameServer
pzexe: classpath: -Djava.class.path=java/:java/jinput.jar:java/lwjgl.jar:java/lwjgl_util.jar:java/sqlite-jdbc-3.8.10.1.jar:java/uncommons-maths-1.2.3.jar
pzexe: vmArg (json) 1: -Xms2048m
pzexe: vmArg (json) 2: -Xmx2048m
pzexe: vmArg (json) 3: -Dzomboid.steam=1
pzexe: vmArg (json) 4: -Dzomboid.znetlog=1
pzexe: vmArg (json) 5: -Djava.library.path=linux64/:natives/
pzexe: vmArg (json) 6: -XX:-UseSplitVerifier
pzexe: vmArg (json) 7: -Djava.security.egd=file:/dev/urandom
pzexe: using jvm "/home/pzserver/serverfiles/jre64/lib/amd64/server/libjvm.so"
pzexe: arg: -ip
pzexe: arg: 149.202.51.89
pzexe: arg: -adminpassword
pzexe: arg: "CHANGE_ME"
pzexe: arg: -servername
pzexe: arg: pzserver
Exception in thread "main" java.lang.UnsatisfiedLinkError: no PZBullet64 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
        at java.lang.Runtime.loadLibrary0(Runtime.java:849)
        at java.lang.System.loadLibrary(System.java:1088)
        at zombie.core.physics.Bullet.init(Bullet.java:38)
        at zombie.network.GameServer.main(GameServer.java:312)
`
```

===UPDATE===

I have reinstalled my vps with Centos 7 (64bit) and reinstaller GSM with vehicle branch for project zomboid, same error:

```
pzexe: arg: pzserver
Exception in thread "main" java.lang.UnsatisfiedLinkError: no PZBullet64 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
        at java.lang.Runtime.loadLibrary0(Runtime.java:849)
        at java.lang.System.loadLibrary(System.java:1088)
        at zombie.core.physics.Bullet.init(Bullet.java:38)
        at zombie.network.GameServer.main(GameServer.java:312)


  
```

**Comment by DrCox1911** [comment]
Not related to LGSM, it's a problem only the game devs can fix (the linkage of the lib PZBullet64 is wrong on linux build)

**Comment by UltimateByte** [comment]
I don't think this is LGSM's fault and that there is any workaround we could do to make it work.

Nice admin password though.

https://github.com/GameServerManagers/LinuxGSM/wiki/Support
