### ISSUE TITLE
Project Zomboid Ubuntu missing GLIBCXX

### ISSUE THREAD

**Issue by Kallb123** [GameServerManagers/LinuxGSM#1918]
This problem is specific to a game, so it might not belong here. However, the LGSM documentation states it supports Ubuntu 12.04+, which appears impossible now as the required version of GLIBCXX needs Ubuntu 16.04

If this is the case, the documents need updating. If this isn't the case, then a solution to the missing file would be most appropriate. 

Specifically, using a fully upgraded version of Ubuntu 14.04.5 LTS, trying to run a server results in a crash after the following part of initialisation:
```
1528925331149 Loading: media/maps/Muldraugh, KY/objects.lua
1528925334597 Max #ZONES on one chunk is 26
1528925334760 Initialising RakNet...
Exception in thread "main" java.lang.UnsatisfiedLinkError: zombie.core.raknet.RakNetPeerInterface.Init(Z)V
        at zombie.core.raknet.RakNetPeerInterface.Init(Native Method)
        at zombie.core.raknet.UdpEngine.<init>(UdpEngine.java:42)
        at zombie.network.GameServer.startServer(GameServer.java:2409)
        at zombie.network.GameServer.main(GameServer.java:671)
[  OK  ] Debug pzserver: Stopping debug
```

This seems tied to an earlier error:
```
1528925316211 Loading RakNet64...
1528925316221 Loading ZNetJNI64...
java.lang.UnsatisfiedLinkError: /home/pzserver/pzserver/serverfiles/natives/libZNetJNI64.so: /home/pzserver/pzserver/serverfiles/natives/libZNetJNI64.so: symbol _ZTVNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1880)        at java.lang.Runtime.loadLibrary0(Runtime.java:849)
        at java.lang.System.loadLibrary(System.java:1088)
        at zombie.core.znet.SteamUtils.loadLibrary(SteamUtils.java:24)
        at zombie.core.znet.SteamUtils.init(SteamUtils.java:73)
        at zombie.network.GameServer.main(GameServer.java:405)
1528925316232 Failed to load networking libraries
```

**Comment by dgibbs64** [comment]
Thanks for this. We will need to investigate :)

**Comment by dgibbs64** [comment]
I have increased the requirements on the website. This might be related
https://stackoverflow.com/questions/36816570/glibcxx-3-4-21-not-defined-in-file-libstdc-so-6-with-link-time-reference

**Comment by Kallb123** [comment]
To anyone in a similar situation (using Ubuntu 14.04 wanting to host latest PZ server)... Docker is a fairly simple solution. There are automated builds out there that will run Ubuntu 16.04 (or later), install LGSM PZ server and boot it all up. Docker + LGSM work great together, making the tasks very simple.
