### ISSUE TITLE
LGSM Barotrauma does not work as of latest update

### ISSUE THREAD

**Issue by atomsite** [GameServerManagers/LinuxGSM#2984]
## User Story
Since updating to the new build of Barotrauma, starting a server has become impossible, I have tested this on a current configuration, updated with `btserver u`, as well as a blank install.

## Basic info

* **Distro:** Debian 10
* **Game:** Barotrauma
* **Command:** ./btserver d
* **LinuxGSM version:** [v20.1.3]

## Further Information

Within the error logs it is pointing to directories that do not exist in my computer, namely /home/joonas, it may be that the startup scripts are using incorrect absolute directories?

```
Barotrauma Debuging
=================================
Distro:       Debian GNU/Linux 10 (buster)
Arch:         x86_64
Kernel:       5.6.0-0.bpo.2-amd64
Hostname:     REDACTED
tmux:         tmux 2.8
Avg Load:     2.36, 2.14, 3.09
Free Memory:  17GB
Free Disk:    58G
glibc required:	2.17
Server IP:	REDACTED
Internet IP:	REDACTED
Server password:	NOT SET
Start parameters:
./DedicatedServer.exe 

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If btserver is already running it will be stopped.

Continue? [Y/n] Y
[ INFO ] Debuging btserver: Stopping any running servers
[ INFO ] Stopping btserver: Server is already stopped
[  OK  ] Stopping btserver: Starting debug
Barotrauma Dedicated Server 0.10.4.0 (ReleaseLinux, branch release, revision 965c31410a)
Loading game settings
Loading MD5 hash cache
Initializing SteamManager
Initializing GameAnalytics
Initializing GameScreen
Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean                                                                                           
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.                                    Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean                                                                                           
Selected sub: Berilia                                                                        
Selected shuttle: Selkie                                                                     
[31/07/2020 19:07:49]
  Starting the server...                                               
[31/07/2020 19:07:49]
  Using Lidgren networking. Manual port forwarding may be required. If players cannot connect to the server, you may want to use the in-game hosting menu (which uses SteamP2P networking and does not require port forwarding).                                   
Coroutine Barotrauma.Networking.GameServer+<StartServer>d__47 threw an exception: InitGameServer returned false (0,56043,27015,27016,2,"1.0.0.0")
   at Steamworks.SteamServer.Init(AppId appid, SteamServerInit init, Boolean asyncCallbacks) in /home/joonas/Barotrauma/Libraries/Facepunch.Steamworks/SteamServer.cs:line 94
   at Barotrauma.Steam.SteamManager.CreateServer(GameServer server, Boolean isPublic) in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/Networking/SteamManager.cs:line 26
   at Barotrauma.Networking.GameServer.StartServer(Boolean isPublic)+MoveNext() in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 195
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 212  
```

**Comment by dgibbs64** [comment]
Just tested this myself and is working for me. I recommend re-installing and seeing if that help

**Comment by Benson92** [comment]
I'm having the same issue after a complete reinstall of steamcmd and barotrauma.

**Comment by dgibbs64** [comment]
It looks like a problem with Barotrauma and not LinuxGSM. You will need to speak with the devs of the game/check there forums on this one

**Comment by h3o66** [comment]
I seems there is a issue on the Gameserver side, Linking here the issue from them:
https://github.com/Regalis11/Barotrauma/issues/2310
