### ISSUE TITLE
Barotrauma server start does not without libicu

### ISSUE THREAD

**Issue by h3o66** [GameServerManagers/LinuxGSM#3082]
## User Story

As a user i want that the 

## Basic info

* **Distro:** [CentOS 8]
* **Game:** [Barotrauma]
* **Command:** [start]
* **LinuxGSM version:** [v20.5.1]

## Further Information

Wtihout the dependency libicu the server does not start and the core is dumped

```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String, System.String)
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Reflection.RuntimeAssembly.GetLocale()
   at System.Reflection.RuntimeAssembly.GetName(Boolean)
   at System.Reflection.Assembly.GetName()
   at Barotrauma.GameMain..cctor()
   at Barotrauma.Program.Main(System.String[])
./DedicatedServer.exe: line 1:  5499 Aborted                 (core dumped) ./DedicatedServer
```

## To Reproduce

Steps to reproduce the behaviour:
1. Install on clean centos
2. start server
3. check console log

## Expected behaviour

starts without a crash

**Comment by h3o66** [comment]
Done in Release 20.6.0
