### ISSUE TITLE
[Bug]: Seven Days to Die Migrating from 20.7 (Stable) to 21 (latest_experimental) won't start

### ISSUE THREAD

**Issue by karenmcd** [GameServerManagers/LinuxGSM#4235]
### User story

As a server admin, I want to migrate from stable to the new experimental branch so that we can play on the new release

### Game

Seven Days to Die

### Linux distro

Debian 11

### Command

command: start

### Further information

After editing:
```
sdtdserver@debian-server:~$ nano lgsm/config-lgsm/sdtdserver/sdtdserver.cfg
```
to say this:
```
# SteamCMD Branch | https://docs.linuxgsm.com/steamcmd/branch
branch="latest_experimental"
betapassword=""
```

After a long update process,  starting it results in this:
```
sdtdserver@debian-server:~$ ./sdtdserver start
/home/sdtdserver/lgsm/modules/info_game.sh: line 134: AND: command not found
/home/sdtdserver/lgsm/modules/info_game.sh: line 134: AND: command not found
[  OK  ] Starting sdtdserver: NOT SET
```
```
System:    Host: debian-server Kernel: 5.10.0-23-amd64 x86_64 bits: 64 Console: tty 1 Distro: Debian GNU/Linux 11 (bullseye)
Machine:   Type: Server System: HP product: ProLiant DL360p Gen8 v: N/A serial: <superuser required>
           Mobo: N/A model: N/A serial: N/A BIOS: HP 
CPU:       Info: 2x Quad Core model: Intel Xeon E5-2643 0 bits: 64 type: MT MCP SMP L2 cache: 20 MiB
           Speed: 2284 MHz min/max: 1200/3500 MHz Core speeds (MHz): 1: 2284 2: 2258 3: 2281 4: 2284 5: 1197 6: 1197 7: 1197
           8: 1197 9: 2287 10: 2287 11: 1197 12: 1197 13: 1197 14: 1197 15: 2268 16: 2277
Graphics:  Message: No Device data found.
           Display: server: No display server data found. Headless machine? tty: 237x64
           Message: Advanced graphics data unavailable in console. Try -G --display
Audio:     Message: No Device data found.
Network:   Device-1: Broadcom NetXtreme BCM5719 Gigabit Ethernet PCIe driver: tg3
           IF: eno1 state: up speed: 1000 Mbps duplex: full mac: 
           Device-2: Broadcom NetXtreme BCM5719 Gigabit Ethernet PCIe driver: tg3
           IF: eno2 state: down mac: 
           Device-3: Broadcom NetXtreme BCM5719 Gigabit Ethernet PCIe driver: tg3
           IF: eno3 state: down mac: 
           Device-4: Broadcom NetXtreme BCM5719 Gigabit Ethernet PCIe driver: tg3
           IF: eno4 state: down mac: 
RAID:      Hardware-1: Hewlett-Packard Smart Array Gen8 Controllers driver: hpsa
Drives:    Local Storage: total: 2.18 TiB used: 105.1 GiB (4.7%)
           ID-1: /dev/sda model: LOGICAL VOLUME size: 2.18 TiB
Partition: ID-1: / size: 233.62 GiB used: 8.13 GiB (3.5%) fs: ext4 dev: /dev/sda3
           ID-2: /home size: 1.91 TiB used: 96.98 GiB (5.0%) fs: ext4 dev: /dev/sda4
Swap:      ID-1: swap-1 type: partition size: 7.45 GiB used: 0 KiB (0.0%) dev: /dev/sda2
Sensors:   System Temperatures: cpu: 50.0 C mobo: N/A
           Fan Speeds (RPM): N/A
Info:      Processes: 190 Uptime: 11d 11h 02m Memory: 125.85 GiB used: 9.7 GiB (7.7%) Init: systemd runlevel: 5 Shell: Bash
           inxi: 3.3.01
```

**Comment by dgibbs64** [comment]
Thanks I will look at all the sdtd issues asap

**Comment by Pathas-Gamer** [comment]
#4222 This is related to having a space in the game name. Several other current issues with SDTD though.

**Comment by karenmcd** [comment]
Starting it looks like this: (more text below/between the code blocks)

```
sdtdserver@debian-server:~$ ./sdtdserver debug
fetching GitHub command_debug.sh...OK

7 Days To Die Debuging
=================================
Distro:          Debian GNU/Linux 11 (bullseye)
Architecture:    x86_64
Kernel:          5.10.0-23-amd64
Hostname:        debian-server
tmux:            tmux 3.1c
Avg Load:        1.24, 1.68, 1.86
Free Memory:     108GB
Free Disk:       1.8T
glibc required: 2.15
Game Server IP: 0.0.0.0:26900
Internet IP:    50.69.216.129:26900
Server password:        ****
Start parameters:
 ./7DaysToDieServer.x86_64 -quit -batchmode -nographics -dedicated -configfile=/home/sdtdserver/serverfiles/sdtdserver.xml

Use debug for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If sdtdserver is already running it will be stopped.

Continue? [Y/n] Y
[ INFO ] Debuging sdtdserver: Stopping any running servers
[ INFO ] Stopping sdtdserver: BLACK AND RED is already stopped
[  OK  ] Debuging sdtdserver: Starting debug
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
Mono path[0] = '/home/sdtdserver/serverfiles/7DaysToDieServer_Data/Managed'
Mono config path = '/home/sdtdserver/serverfiles/7DaysToDieServer_Data/MonoBleedingEdge/etc'
Shutdown handler: initialize.
Preloaded 'libEOSSDK-Linux-Shipping.so'
Preloaded 'libMagick.so'
Preloaded 'lib_burst_generated.so'
Preloaded 'libgetrss.so'
Preloaded 'libsteam_api.so'
Preloaded 'steamclient.so'
Unable to preload the following plugins:
        libMouseLib.so
Loading player data from /home/sdtdserver/serverfiles/7DaysToDieServer_Data/data.unity3d
Initialize engine version: 2021.3.19f1 (c9714fde33b6)
[Subsystems] Discovering subsystems at path /home/sdtdserver/serverfiles/7DaysToDieServer_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0; jobified=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
FMOD failed to initialize the output device.: "Error initializing output device. " (60)
Forced to initialize FMOD to to the device driver's system output rate 48000, this may impact performance and/or give inconsistent experiences compared to selected sample rate 48000
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
FMOD failed to initialize the output device.: "Error initializing output device. " (60)
FMOD initialized on nosound output
Begin MonoManager ReloadAssembly
- Completed reload, in  0.146 seconds
ERROR: Shader Sprites/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Sprites/Mask shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Legacy Shaders/VertexLit shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Legacy Shaders/Diffuse' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Legacy Shaders/Diffuse shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Legacy Shaders/Diffuse' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
WARNING: Shader Unsupported: '7DTD/Cube_UI_Frame' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader 7DTD/Cube_UI_Frame shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: '7DTD/Cube_UI_Frame' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader GUI/Text Shader shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Unlit/Transparent Colored shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: '7DTD/Cube_UI_Glow' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader 7DTD/Cube_UI_Glow shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: '7DTD/Cube_UI_Glow' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
UnloadTime: 1.642602 ms
Fallback handler could not load library /home/sdtdserver/serverfiles/7DaysToDieServer_Data/MonoBleedingEdge/x86_64/data-0x1bf4a50.so
Fallback handler could not load library /home/sdtdserver/serverfiles/7DaysToDieServer_Data/MonoBleedingEdge/x86_64/data-0x20ad3a0.so
2023-06-24T16:23:47 0.560 INF Version: Alpha 21 (b317) Compatibility Version: Alpha 21, Build: LinuxPlayer 64 Bit
2023-06-24T16:23:47 0.562 INF System information:
2023-06-24T16:23:47 0.562 INF    OS: Linux 5.10 Debian GNU/Linux 11 64bit
2023-06-24T16:23:47 0.583 INF    CPU: Intel(R) Xeon(R) CPU E5-2643 0 @ 3.30GHz (cores: 16)
2023-06-24T16:23:47 0.583 INF    RAM: 128865 MB
2023-06-24T16:23:47 0.584 INF    GPU: Null Device (128 MB)
2023-06-24T16:23:47 0.588 INF    Graphics API: NULL 1.0 [1.0] (shader level 5.0)
2023-06-24T16:23:47 0.588 INF Last played version: Alpha 21
2023-06-24T16:23:47 0.592 INF Local UTC offset: -7 hours
2023-06-24T16:23:47 0.621 INF Command line arguments: ./7DaysToDieServer.x86_64 -quit -batchmode -nographics -dedicated -configfile=/home/sdtdserver/serverfiles/sdtdserver.xml
2023-06-24T16:23:47 0.624 INF Parsing server configfile: /home/sdtdserver/serverfiles/sdtdserver.xml
2023-06-24T16:23:47 0.671 ERR ====================================================================================================
2023-06-24T16:23:47 0.671 ERR Error parsing configfile property 'ControlPanelEnabled': Unknown config option
2023-06-24T16:23:47 0.671 INF Make sure your configfile is updated the current server version!
2023-06-24T16:23:47 0.671 INF Startup aborted due to the given error in server configfile
2023-06-24T16:23:47 0.671 ERR ====================================================================================================
Caught fatal signal - signo:11 code:1 errno:0 addr:0x50
Obtained 10 stack frames.
#0  0x007f2e3b9ba140 in funlockfile
#1  0x007f2e3c89b247 in std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_erase(std::_Rb_tree_node<void const*>*)
#2  0x007f2e3c7b2fab in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_erase(std::_Rb_tree_node<int>*)
#3  0x007f2e3c7aff3c in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_erase(std::_Rb_tree_node<int>*)
#4  0x007f2e3c7af9b5 in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_erase(std::_Rb_tree_node<int>*)
#5  0x007f2e3c84d8bf in std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_erase(std::_Rb_tree_node<void const*>*)
#6  0x007f2e3c79362e in int* std::_V2::__rotate<int*>(int*, int*, int*, std::random_access_iterator_tag)
#7  0x007f2e3c9c0994 in PlayerMain(int, char**)
#8  0x007f2e3b7f6d0a in __libc_start_main
#9  0x00000000201029 in (Unknown)
/home/sdtdserver/lgsm/modules/command_debug.sh: line 121: 3619754 Segmentation fault      ./7DaysToDieServer.x86_64 -quit -batchmode -nographics -dedicated -configfile=/home/sdtdserver/serverfiles/sdtdserver.xml
[ ERROR ] Debuging sdtdserver: Server has stopped: exit code: 0
[ ERROR ] Debuging sdtdserver: Press ENTER to exit debug mode
[  OK  ] Debuging sdtdserver: Stopping debug
```

the error seems to me to be located in the configuration file - Here's the line it says is an error and the line above and below:

```
sdtdserver@debian-server:~$ nano /home/sdtdserver/serverfiles/sdtdserver.xml

        <property name="ServerAdminSlotsPermission"             value="1"/>                                             <!-- Required permission level to use the admin slots above -->

        <!-- Admin interfaces -->
        <property name="ControlPanelEnabled"                    value="false"/>                         <!-- Enable/Disable the web control panel -->
        <property name="ControlPanelPort"                       value="8080"/>                          <!-- Port of the control panel webpage -->
```

Changing the value of ControlPanelenEabled to "0" results in the exact same debug output error.

I didn't have issues with a space in the name of the server prior to trying to migrate to latest_experimental. I'm not sure if this is relevant, but thought i'd bring that up too.

**Comment by karenmcd** [comment]
and in fact have the exact same error with ALL spaces removed from description and game name:

```
sdtdserver@debian-server:~$ ./sdtdserver debug

7 Days To Die Debuging
=================================
Distro:          Debian GNU/Linux 11 (bullseye)
Architecture:    x86_64
Kernel:          5.10.0-23-amd64
Hostname:        debian-server
tmux:            tmux 3.1c
Avg Load:        1.29, 1.25, 1.36
Free Memory:     108GB
Free Disk:       1.8T
glibc required: 2.15
Game Server IP: 0.0.0.0:26900
Internet IP:    50.69.216.129:26900
Server password:        ****
Start parameters:
 ./7DaysToDieServer.x86_64 -quit -batchmode -nographics -dedicated -configfile=/home/sdtdserver/serverfiles/sdtdserver.xml

Use debug for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If sdtdserver is already running it will be stopped.

Continue? [Y/n] Y
[ INFO ] Debuging sdtdserver: Stopping any running servers
[ INFO ] Stopping sdtdserver: BLACKANDRED is already stopped
[  OK  ] Debuging sdtdserver: Starting debug
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
Mono path[0] = '/home/sdtdserver/serverfiles/7DaysToDieServer_Data/Managed'
Mono config path = '/home/sdtdserver/serverfiles/7DaysToDieServer_Data/MonoBleedingEdge/etc'
Shutdown handler: initialize.
Preloaded 'libEOSSDK-Linux-Shipping.so'
Preloaded 'libMagick.so'
Preloaded 'lib_burst_generated.so'
Preloaded 'libgetrss.so'
Preloaded 'libsteam_api.so'
Preloaded 'steamclient.so'
Unable to preload the following plugins:
        libMouseLib.so
Loading player data from /home/sdtdserver/serverfiles/7DaysToDieServer_Data/data.unity3d
Initialize engine version: 2021.3.19f1 (c9714fde33b6)
[Subsystems] Discovering subsystems at path /home/sdtdserver/serverfiles/7DaysToDieServer_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0; jobified=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
FMOD failed to initialize the output device.: "Error initializing output device. " (60)
Forced to initialize FMOD to to the device driver's system output rate 48000, this may impact performance and/or give inconsistent experiences compared to selected sample rate 48000
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
FMOD failed to initialize the output device.: "Error initializing output device. " (60)
FMOD initialized on nosound output
Begin MonoManager ReloadAssembly
- Completed reload, in  0.207 seconds
ERROR: Shader Sprites/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Sprites/Mask shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Legacy Shaders/VertexLit shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Legacy Shaders/Diffuse' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Legacy Shaders/Diffuse shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Legacy Shaders/Diffuse' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
WARNING: Shader Unsupported: '7DTD/Cube_UI_Frame' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader 7DTD/Cube_UI_Frame shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: '7DTD/Cube_UI_Frame' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader GUI/Text Shader shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Unlit/Transparent Colored shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: '7DTD/Cube_UI_Glow' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader 7DTD/Cube_UI_Glow shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: '7DTD/Cube_UI_Glow' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
UnloadTime: 1.424854 ms
Fallback handler could not load library /home/sdtdserver/serverfiles/7DaysToDieServer_Data/MonoBleedingEdge/x86_64/data-0x22dc530.so
Fallback handler could not load library /home/sdtdserver/serverfiles/7DaysToDieServer_Data/MonoBleedingEdge/x86_64/data-0x27240d0.so
2023-06-24T16:55:43 0.565 INF Version: Alpha 21 (b317) Compatibility Version: Alpha 21, Build: LinuxPlayer 64 Bit
2023-06-24T16:55:43 0.567 INF System information:
2023-06-24T16:55:43 0.567 INF    OS: Linux 5.10 Debian GNU/Linux 11 64bit
2023-06-24T16:55:43 0.585 INF    CPU: Intel(R) Xeon(R) CPU E5-2643 0 @ 3.30GHz (cores: 16)
2023-06-24T16:55:43 0.585 INF    RAM: 128865 MB
2023-06-24T16:55:43 0.586 INF    GPU: Null Device (128 MB)
2023-06-24T16:55:43 0.590 INF    Graphics API: NULL 1.0 [1.0] (shader level 5.0)
2023-06-24T16:55:43 0.590 INF Last played version: Alpha 21
2023-06-24T16:55:43 0.594 INF Local UTC offset: -7 hours
2023-06-24T16:55:43 0.623 INF Command line arguments: ./7DaysToDieServer.x86_64 -quit -batchmode -nographics -dedicated -configfile=/home/sdtdserver/serverfiles/sdtdserver.xml
2023-06-24T16:55:43 0.626 INF Parsing server configfile: /home/sdtdserver/serverfiles/sdtdserver.xml
2023-06-24T16:55:43 0.674 ERR ====================================================================================================
2023-06-24T16:55:43 0.674 ERR Error parsing configfile property 'ControlPanelEnabled': Unknown config option
2023-06-24T16:55:43 0.674 INF Make sure your configfile is updated the current server version!
2023-06-24T16:55:43 0.674 INF Startup aborted due to the given error in server configfile
2023-06-24T16:55:43 0.674 ERR ====================================================================================================
Caught fatal signal - signo:11 code:1 errno:0 addr:0x50
Obtained 10 stack frames.
#0  0x007f33aa7be140 in funlockfile
#1  0x007f33ab69f247 in std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_erase(std::_Rb_tree_node<void const*>*)
#2  0x007f33ab5b6fab in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_erase(std::_Rb_tree_node<int>*)
#3  0x007f33ab5b3f3c in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_erase(std::_Rb_tree_node<int>*)
#4  0x007f33ab5b39b5 in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_erase(std::_Rb_tree_node<int>*)
#5  0x007f33ab6518bf in std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_erase(std::_Rb_tree_node<void const*>*)
#6  0x007f33ab59762e in int* std::_V2::__rotate<int*>(int*, int*, int*, std::random_access_iterator_tag)
#7  0x007f33ab7c4994 in PlayerMain(int, char**)
#8  0x007f33aa5fad0a in __libc_start_main
#9  0x00000000201029 in (Unknown)
/home/sdtdserver/lgsm/modules/command_debug.sh: line 121: 3629953 Segmentation fault      ./7DaysToDieServer.x86_64 -quit -batchmode -nographics -dedicated -configfile=/home/sdtdserver/serverfiles/sdtdserver.xml
[ ERROR ] Debuging sdtdserver: Server has stopped: exit code: 0
[ ERROR ] Debuging sdtdserver: Press ENTER to exit debug mode
^C
```
