### ISSUE TITLE
[Bug]: Wurm docker container does not start server

### ISSUE THREAD

**Issue by zackchadwick** [GameServerManagers/LinuxGSM#4265]
### User story

As a Docker user, I want the Wurm server to start so that I can host the server.

### Game

Wurm

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

When starting the ghcr.io/gameservermanagers/gameserver:wurm image the server does not start, either automatically, manually using the /app/wurmserver launcher, or by manually running the execution command.

The issue appears to be due to Java within the container.

I was able to troubleshoot this issue by adding the repository list back into the container and installing the openjdk-8-jre package. After that is present in the container the server will launch without any issues.

I'm opening this issue to link to a pull request for updating the dependency list so that it is included in the container going forward.

### Relevant log output

```shell
Output from ./wurmserver st being run manually:

$ ./wurmserver st
[  OK  ] Starting wurmserver: Test server
[ INFO ] Stopping wurmserver: Test server is already stopped
[  OK  ] Starting wurmserver: Test server
Error! Command did not exit correctly: st

core_exit.sh exiting with code: 2


Output from using the execution command manually in the /data/serverfiles directory:

$ xvfb-run ./WurmServerLauncher ADMINPWD="adminYijhc94Z" EPICSETTINGS="false" EXTERNALPORT="3724" HOMESERVER="true" HOMEKINGDOM="4" LOGINSERVER="true" MAXPLAYERS="200" QUERYPORT="27017" SERVERNAME="LinuxGSM" SERVERPASSWORD="" START="Creative" IP=""
Starting
Logs found: 0
SteamAppId set.
/data/serverfiles
Runtime path: /data/serverfiles/runtime/jre1.8.0_172/lib/amd64/server/libjvm.so
Working Directory: /data/serverfiles
Number of options: 7
Create java VM!
Jul 14, 2023 1:08:33 PM com.wurmonline.server.gui.WurmServerGuiMain main
INFO: WurmServerGuiMain starting
Should start without GUI here!

Execution from starting without any parameters (per the fix_wurm.sh) to generate the Creative/Adventure directories:

$ xvfb-run ./WurmServerLauncher
Starting
Logs found: 0
SteamAppId set.
/data/serverfiles
Runtime path: /data/serverfiles/runtime/jre1.8.0_172/lib/amd64/server/libjvm.so
Working Directory: /data/serverfiles
Number of options: 7
Create java VM!
Jul 14, 2023 1:09:11 PM com.wurmonline.server.gui.WurmServerGuiMain main
INFO: WurmServerGuiMain starting
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:248)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
```

### Steps to reproduce

1. Download the ghcr.io/gameservermanagers/gameserver:wurm image
2. Run the container
3. The server will not launch

**Comment by dgibbs64** [comment]
I have completed a significant rework of wurm server to get it correctly working again. Will be available in the next release
