### ISSUE TITLE
[Bug]: Core Keeper - Missing dependency libxi6

### ISSUE THREAD

**Issue by Kylindrias** [GameServerManagers/LinuxGSM#4638]
### User story

Installed Core Keeper on my LGSM server as per usual but I kept getting "Unable to start LinuxGSM" and a seg fault in the server logs.

### Game

Core Keeper

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

So this is actually an old bug that may be a regression or something. I'm running Ubuntu Server 22.04.4 LTS as a virtual guest.

See https://github.com/GameServerManagers/LinuxGSM/issues/4175

Basically the exact same issue, when attempting to start the server I get an error "unable to start LinuxGSM" and the server logs show segmentation fault.

I tried the fix mentioned in the link above (sudo apt install libxi6) and that immediately fixed the issue.

I'll note that I spent hours trying to fix this and during troubleshooting I tried installing on a Ubuntu Server 24.04 in VMWare.

It worked straight away after install, so it's possible this bug is limited only to Ubuntu 22.04 but not Ubuntu 24.04.

### Relevant log output

```shell
cat log/server/ckserver-game.log 
Mono path[0] = '/home/ckserver/serverfiles/CoreKeeperServer_Data/Managed'
Mono config path = '/home/ckserver/serverfiles/CoreKeeperServer_Data/MonoBleedingEdge/etc'
Preloaded 'discord_game_sdk.so'
Shutdown handler: initialize.
Preloaded 'libEOSSDK-Linux-Shipping.so'
Preloaded 'libPlayFabMultiplayer.so'
Preloaded 'lib_burst_generated.so'
Preloaded 'libparty.so'
Preloaded 'libsentry.so'
Preloaded 'libsteam_api.so'
Display 0 '0': 1280x1024 (primary device).
[Physics::Module] Initialized MultithreadedJobDispatcher with 3 workers.
Loading player data from /home/ckserver/serverfiles/CoreKeeperServer_Data/data.unity3d
Unable to load player prefs
Desktop is 1280 x 1024 @ 0 Hz
Caught fatal signal - signo:11 code:1 errno:0 addr:(nil)
Obtained 16 stack frames.
#0  0x007f9310a65520 in __sigaction
#1             (nil) in (Unknown)
#2  0x007f93126a0e35 in PlayerMain(int, char**)
#3  0x007f93126a040f in PlayerMain(int, char**)
#4  0x007f931267f0e7 in PlayerMain(int, char**)
#5  0x007f931269fc43 in PlayerMain(int, char**)
#6  0x007f931267e4e3 in PlayerMain(int, char**)
#7  0x007f9312648698 in PlayerMain(int, char**)
#8  0x007f931267de2c in PlayerMain(int, char**)
#9  0x007f9311bd0e98 in PlayerMain(int, char**)
#10 0x007f93123b54f5 in PlayerMain(int, char**)
#11 0x007f93123b506b in PlayerMain(int, char**)
#12 0x007f9311bbfed1 in PlayerMain(int, char**)
#13 0x007f9310a4cd90 in __libc_init_first
#14 0x007f9310a4ce40 in __libc_start_main
#15 0x00000000201029 in (Unknown)
```

### Steps to reproduce

Install Core Keeper server using LGSM on Ubuntu 22.04
Attempt to start server.
Install libxi6 and now it works.

**Comment by sebastienvercammen** [comment]
I can confirm, just had the same thing happen to me. Latest version of everything, missing libxi6. Installing it by hand fixed it.

**Comment by dgibbs64** [comment]
So there is a missing dependency. I will get that looked at for next release

**Comment by dgibbs64** [comment]
I tested with with teh latest develop branch and its working. So if it is still not working it should be by next release

**Comment by Furane** [comment]
The libxi6 dependancy is still missing at installation! It creates segfault.
Please fix it!

**Comment by dgibbs64** [comment]
I have just checked the latest release and it does install the dependency.

![Image](https://github.com/user-attachments/assets/df58beb2-c266-476e-9346-635f3e75e56c)

**Comment by Furane** [comment]
> I have just checked the latest release and it does install the dependency.
> 
> ![Image](https://github.com/user-attachments/assets/df58beb2-c266-476e-9346-635f3e75e56c)

Ok, so maybe I didn't have the lastest release
