### ISSUE TITLE
[Bug]: eco v11 not starting without changing startparameters

### ISSUE THREAD

**Issue by A-xis** [GameServerManagers/LinuxGSM#4723]
### User story

Eco v11+ now require authentification to Strange Cloud to be able to start

### Game

eco

### Linux distro

RedHat 9

### Command

command: start

### Further information

When starting an Eco v11 server, the game fail to do so, due to changes on requirements:
![image (2)](https://github.com/user-attachments/assets/bfbd0788-c209-45e0-87b3-beba495d1d64)

You now need to setup (in _../lgsm/config-lgsm/ecoserver/ecoserver.cfg_ )
startparameters="-nogui -userToken="<token here>"

You can generate the token from https://play.eco/account

Other options are available, but usertoken seems to be the safest.

This should be at least indicated on https://linuxgsm.com/servers/ecoserver/#v-pills-install

### Relevant log output

```shell
Failed to start the server. Exception was Exception: Exception
Message:Authentication to Strange Cloud failed. No authentication methods were available. Provide valid credentials ('-username' and '-password' or '-userToken' or '-steamTicket') or use '-offline' to start server in offline mode.
Source:EcoServer
System.Exception: Authentication to Strange Cloud failed. No authentication methods were available. Provide valid credentials ('-username' and '-password' or '-userToken' or '-steamTicket') or use '-offline' to start server in offline mode.
at Eco.Server.StrangeCloudLogin.Initialize()
at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
```

### Steps to reproduce

1. Install Eco with current lgsm setup guide
2. Start the game
3. Look at the _log/console/ecoserver-console.log_ logfile

**Comment by mycide** [comment]
Can anyone please post the work around while this fix is backlogged?
I see the line that needs to be added, above, but I am not sure where that would need to be added.
Thank you :)

**Comment by A-xis** [comment]
Updated description to also include file path as requested
(It's _../lgsm/config-lgsm/ecoserver/ecoserver.cfg_ )
